// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:kendedes_mobile/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BuildingStatusAdapter());
    registerAdapter(OrganizationAdapter());
    registerAdapter(ProjectAdapter());
    registerAdapter(ProjectTypeAdapter());
    registerAdapter(SectorAdapter());
    registerAdapter(TagDataAdapter());
    registerAdapter(TagTypeAdapter());
    registerAdapter(UserAdapter());
    registerAdapter(UserRoleAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(BuildingStatusAdapter());
    registerAdapter(OrganizationAdapter());
    registerAdapter(ProjectAdapter());
    registerAdapter(ProjectTypeAdapter());
    registerAdapter(SectorAdapter());
    registerAdapter(TagDataAdapter());
    registerAdapter(TagTypeAdapter());
    registerAdapter(UserAdapter());
    registerAdapter(UserRoleAdapter());
  }
}
